version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=nodee
      - POSTGRES_USER=alejandro
      - POSTGRES_PASSWORD=admin123
    ports:
      - 54320:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
